import type { RelationshipType, MoodType, ExperienceMode, SceneConfiguration } from '../../types/schema.ts';

export interface VisualTheme {
  bg: string;
  bgGradient: string;
  accent: string;
  accentHover: string;
  textPrimary: string;
  textSecondary: string;
  cardBg: string;
  border: string;
  fontClass: string;
  particles: 'confetti' | 'stars' | 'hearts' | 'bubbles' | 'dust' | 'none';
}

export interface TemplateDefinition {
  id: string;
  version: string;
  name: string;
  tagline: string;
  description: string;
  category: 'bestie' | 'sibling' | 'family' | 'romantic' | 'cinematic' | 'retro' | 'playful' | 'cosmic' | 'editorial' | 'intimate';
  relationships: RelationshipType[];
  moods: MoodType[];
  experienceMode: ExperienceMode;
  interactionLevel: 'gentle' | 'balanced' | 'interactive' | 'game';
  visualTheme: VisualTheme;
  defaultScenes: SceneConfiguration[];
  supportsAudio: boolean;
  supportsVideo: boolean;
  supportsPhoto: boolean;
  supports3D: boolean;
  zeroPhotoSafe: boolean;
}

const BASE_THEMES: Record<string, VisualTheme> = {
  nightsky: {
    bg: '#050714',
    bgGradient: 'from-slate-950 via-indigo-950 to-purple-950',
    accent: '#818cf8',
    accentHover: '#6366f1',
    textPrimary: '#f8fafc',
    textSecondary: '#cbd5e1',
    cardBg: 'rgba(15, 23, 42, 0.75)',
    border: 'rgba(99, 102, 241, 0.3)',
    fontClass: 'font-serif',
    particles: 'stars'
  },
  neon: {
    bg: '#090a0f',
    bgGradient: 'from-zinc-950 via-neutral-900 to-fuchsia-950',
    accent: '#f43f5e',
    accentHover: '#e11d48',
    textPrimary: '#ffffff',
    textSecondary: '#fda4af',
    cardBg: 'rgba(24, 24, 27, 0.85)',
    border: 'rgba(244, 63, 94, 0.4)',
    fontClass: 'font-mono',
    particles: 'confetti'
  },
  cozy: {
    bg: '#1c1612',
    bgGradient: 'from-amber-950 via-stone-900 to-orange-950',
    accent: '#fbbf24',
    accentHover: '#f59e0b',
    textPrimary: '#fef3c7',
    textSecondary: '#fde68a',
    cardBg: 'rgba(41, 37, 36, 0.8)',
    border: 'rgba(251, 191, 36, 0.25)',
    fontClass: 'font-sans',
    particles: 'dust'
  },
  paper: {
    bg: '#171412',
    bgGradient: 'from-stone-900 via-neutral-900 to-warm-gray-900',
    accent: '#d97706',
    accentHover: '#b45309',
    textPrimary: '#fffbeb',
    textSecondary: '#e7e5e4',
    cardBg: 'rgba(28, 25, 23, 0.9)',
    border: 'rgba(217, 119, 6, 0.35)',
    fontClass: 'font-serif',
    particles: 'none'
  },
  luxury: {
    bg: '#0a0a0a',
    bgGradient: 'from-black via-zinc-950 to-neutral-900',
    accent: '#e2e8f0',
    accentHover: '#ffffff',
    textPrimary: '#ffffff',
    textSecondary: '#a1a1aa',
    cardBg: 'rgba(18, 18, 18, 0.9)',
    border: 'rgba(255, 255, 255, 0.15)',
    fontClass: 'font-serif',
    particles: 'dust'
  },
  playful: {
    bg: '#0f172a',
    bgGradient: 'from-sky-950 via-indigo-950 to-pink-950',
    accent: '#38bdf8',
    accentHover: '#0ea5e9',
    textPrimary: '#f0f9ff',
    textSecondary: '#bae6fd',
    cardBg: 'rgba(30, 41, 59, 0.8)',
    border: 'rgba(56, 189, 248, 0.3)',
    fontClass: 'font-sans',
    particles: 'confetti'
  },
  romantic: {
    bg: '#1a0d18',
    bgGradient: 'from-rose-950 via-stone-950 to-pink-950',
    accent: '#fb7185',
    accentHover: '#f43f5e',
    textPrimary: '#fff1f2',
    textSecondary: '#fecdd3',
    cardBg: 'rgba(35, 18, 30, 0.85)',
    border: 'rgba(251, 113, 133, 0.3)',
    fontClass: 'font-serif',
    particles: 'hearts'
  }
};

const DEFAULT_SCENES = (title: string, mode: ExperienceMode): SceneConfiguration[] => [
  { id: 'sc_open', order: 1, type: 'opening', title: 'A Special Day', subtitle: 'Someone made this universe just for you', durationSeconds: 6, particles: 'stars' },
  { id: 'sc_curiosity', order: 2, type: 'curiosity', title: 'Remember when...', subtitle: 'Every year brings something extraordinary', durationSeconds: 8, particles: 'dust' },
  { id: 'sc_reveal', order: 3, type: 'reveal', title: 'Happy Birthday!', subtitle: 'You brighten every room you enter', durationSeconds: 10, particles: 'confetti' },
  { id: 'sc_interact', order: 4, type: 'interaction', title: 'Make a Wish', subtitle: 'Blow the candles or tap to celebrate', durationSeconds: 12, particles: 'stars' },
  { id: 'sc_message', order: 5, type: 'message', title: 'From the Heart', subtitle: 'Words crafted with love', durationSeconds: 15, particles: 'none' },
  { id: 'sc_finale', order: 6, type: 'finale', title: 'The Universe Celebrates You', subtitle: 'May this year be your brightest chapter yet', durationSeconds: 12, particles: 'confetti' }
];

export const TEMPLATES_CATALOG: TemplateDefinition[] = [
  // --- BESTIES & CHAOS ---
  {
    id: 'night-sky',
    version: '1.0.0',
    name: 'The Night Sky',
    tagline: 'Interactive stars spelling their name across a cosmic sky.',
    description: 'A breathtaking cosmic universe where interactive stars reveal memories and culminate in a brilliant birthday constellation.',
    category: 'cosmic',
    relationships: ['bestie', 'friend', 'partner', 'sister', 'mom'],
    moods: ['cosmic', 'aesthetic', 'magical', 'dreamy', 'midnight'],
    experienceMode: 'nightsky',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.nightsky,
    defaultScenes: DEFAULT_SCENES('The Night Sky', 'nightsky'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: true,
    zeroPhotoSafe: true
  },
  {
    id: 'chaos-bestie',
    version: '1.0.0',
    name: 'Chaos Bestie',
    tagline: 'Unfiltered laughter, inside jokes, and emergency compliments.',
    description: 'High-energy celebration bursting with memes, friendly roasts, and an interactive emergency praise button.',
    category: 'bestie',
    relationships: ['bestie', 'friend', 'sister', 'brother', 'cousin'],
    moods: ['chaotic', 'funny', 'playful', 'neon'],
    experienceMode: 'arcade',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Chaos Bestie', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'midnight-bestie',
    version: '1.0.0',
    name: 'Midnight Bestie',
    tagline: 'Late-night phone calls, neon reflections, and ride-or-die love.',
    description: 'Moody, aesthetic midnight atmosphere reflecting late-night conversations and unbreakable bonds.',
    category: 'bestie',
    relationships: ['bestie', 'friend', 'sister', 'partner'],
    moods: ['midnight', 'aesthetic', 'emotional', 'cozy'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.nightsky,
    defaultScenes: DEFAULT_SCENES('Midnight Bestie', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'ride-or-die',
    version: '1.0.0',
    name: 'Ride or Die',
    tagline: 'Through every plot twist, bad idea, and shared victory.',
    description: 'An ode to loyalty, partnership in crime, and surviving life together.',
    category: 'bestie',
    relationships: ['bestie', 'friend', 'brother', 'sister'],
    moods: ['wholesome', 'emotional', 'playful'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.playful,
    defaultScenes: DEFAULT_SCENES('Ride or Die', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'roast-to-love',
    version: '1.0.0',
    name: 'Roast → Love',
    tagline: 'Start with ruthless banter, end with undeniable sweetness.',
    description: 'Playful teasing transforms into an unexpected emotional declaration of how much they mean to you.',
    category: 'bestie',
    relationships: ['bestie', 'friend', 'brother', 'sister', 'cousin'],
    moods: ['funny', 'chaotic', 'emotional'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Roast → Love', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'bestie-arcade',
    version: '1.0.0',
    name: 'Bestie Arcade',
    tagline: 'Playable 8-bit birthday mini-games and high-score celebrations.',
    description: 'Retro pixel-styled arcade with interactive mini-challenges and celebratory retro sounds.',
    category: 'retro',
    relationships: ['bestie', 'friend', 'brother', 'cousin'],
    moods: ['pixel', 'retro', 'playful'],
    experienceMode: 'arcade',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Bestie Arcade', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'friendship-radio',
    version: '1.0.0',
    name: 'Friendship Radio',
    tagline: 'Broadcasting dedications, top charts, and special birthday airwaves.',
    description: 'Audio cassette and vintage radio broadcast styling where wishes come alive as on-air call-in dedications.',
    category: 'retro',
    relationships: ['bestie', 'friend', 'sister', 'brother'],
    moods: ['retro', 'aesthetic', 'cozy'],
    experienceMode: 'radio',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Friendship Radio', 'radio'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'bestie-chat',
    version: '1.0.0',
    name: 'Bestie Chat',
    tagline: 'A playful messaging UI revealing memories message by message.',
    description: 'Simulates a lively messaging interface with typing indicators, funny stickers, and heartfelt voice notes.',
    category: 'bestie',
    relationships: ['bestie', 'friend', 'sister', 'brother'],
    moods: ['playful', 'cute', 'modern'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.playful,
    defaultScenes: DEFAULT_SCENES('Bestie Chat', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'level-up-bestie',
    version: '1.0.0',
    name: 'Level Up Bestie',
    tagline: 'Unlocked a new year of wisdom, charisma, and questionable decisions.',
    description: 'RPG game-style character sheet showing birthday person stats, special perks, and level up fanfares.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'brother', 'cousin'],
    moods: ['playful', 'pixel', 'funny'],
    experienceMode: 'arcade',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Level Up Bestie', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'classified-bestie-file',
    version: '1.0.0',
    name: 'Classified Bestie File',
    tagline: 'Top secret clearance required: Agent Birthday Dossier.',
    description: 'Confidential agent dossier with classified stamp animations, redacted inside jokes, and mission directives.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'brother', 'sister'],
    moods: ['dark', 'funny', 'playful'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Classified Bestie File', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'digital-scrapbook',
    version: '1.0.0',
    name: 'Digital Scrapbook',
    tagline: 'Washi tape, polaroid pins, handwritten scribbles, and pressed flowers.',
    description: 'Handmade scrapbook aesthetic with tactile peelable stickers, paper textures, and cozy warmth.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'sister', 'mom', 'partner'],
    moods: ['scrapbook', 'handwritten', 'aesthetic', 'cozy'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Digital Scrapbook', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'best-friend-awards',
    version: '1.0.0',
    name: 'Best Friend Awards',
    tagline: 'And the trophy for Best Person to Vent To goes to...',
    description: 'Gold gala ceremony honoring their finest traits with customizable award categories and standing ovations.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'sister', 'brother'],
    moods: ['luxury', 'funny', 'playful'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Best Friend Awards', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'one-more-thing',
    version: '1.0.0',
    name: 'One More Thing',
    tagline: 'A keynote style presentation unveiling their greatest year yet.',
    description: 'Sleek, minimalist product reveal styling delivering punchy, stylish praise and a dramatic finale.',
    category: 'editorial',
    relationships: ['bestie', 'friend', 'colleague', 'brother'],
    moods: ['minimal', 'modern', 'luxury'],
    experienceMode: 'cinematic',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('One More Thing', 'cinematic'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'bestie-mission',
    version: '1.0.0',
    name: 'Bestie Mission',
    tagline: 'Your mission, should you choose to accept: Celebrate without limits.',
    description: 'Spy thriller theme with countdown timers, mission blueprints, and unlocked surprise codes.',
    category: 'playful',
    relationships: ['bestie', 'brother', 'friend', 'cousin'],
    moods: ['chaotic', 'playful', 'neon'],
    experienceMode: 'story',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Bestie Mission', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'friendship-hq',
    version: '1.0.0',
    name: 'Friendship HQ',
    tagline: 'The command center dedicated 100% to celebrating your human.',
    description: 'Interactive control room dashboard monitoring vital friendship stats, inside joke frequencies, and celebration radars.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'brother', 'sister'],
    moods: ['modern', 'neon', 'playful'],
    experienceMode: 'room',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Friendship HQ', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'friendship-constellation',
    version: '1.0.0',
    name: 'Friendship Constellation',
    tagline: 'Connecting our shared milestones into a permanent sky map.',
    description: 'Every memory becomes an interactive glowing star that forms a custom birthday constellation.',
    category: 'cosmic',
    relationships: ['bestie', 'friend', 'sister', 'partner'],
    moods: ['cosmic', 'aesthetic', 'magical'],
    experienceMode: 'nightsky',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.nightsky,
    defaultScenes: DEFAULT_SCENES('Friendship Constellation', 'nightsky'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: true,
    zeroPhotoSafe: true
  },
  {
    id: 'late-night-call',
    version: '1.0.0',
    name: 'Late Night Call',
    tagline: 'For the one who answers at 2 AM without asking questions.',
    description: 'Intimate audio-first experience featuring cozy rain sounds, handwritten notes, and soft glowing lights.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'partner', 'sister'],
    moods: ['cozy', 'rainy', 'midnight', 'emotional'],
    experienceMode: 'letter',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Late Night Call', 'letter'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'chaos-museum',
    version: '1.0.0',
    name: 'Chaos Museum',
    tagline: 'Curating the most iconic, unhinged moments of our history.',
    description: 'Virtual gallery exhibition displaying historical artifacts of friendship chaos with witty placards.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'sister', 'brother', 'cousin'],
    moods: ['chaotic', 'funny', 'editorial'],
    experienceMode: 'museum',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Chaos Museum', 'museum'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'bestie-vault',
    version: '1.0.0',
    name: 'Bestie Vault',
    tagline: 'Spin the combination dial to unlock years of memories.',
    description: 'Bank vault safe door with an interactive combination lock revealing hidden wishes and treasures.',
    category: 'playful',
    relationships: ['bestie', 'brother', 'sister', 'cousin'],
    moods: ['luxury', 'mystical', 'playful'],
    experienceMode: 'magicbox',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Bestie Vault', 'magicbox'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'friendship-cinema',
    version: '1.0.0',
    name: 'Friendship Cinema',
    tagline: 'Your life, directed by love. Opening credits rolling now.',
    description: 'Cinematic film letterbox styling with vintage film grain, soundtrack swells, and director cuts.',
    category: 'cinematic',
    relationships: ['bestie', 'friend', 'partner', 'family'],
    moods: ['cinematic', 'emotional', 'luxury'],
    experienceMode: 'cinematic',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Friendship Cinema', 'cinematic'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'inside-joke-machine',
    version: '1.0.0',
    name: 'Inside Joke Machine',
    tagline: 'Only you two will understand what happens when you pull the lever.',
    description: 'Interactive slot-machine and gumball dispenser generating your shared inside jokes and references.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'brother', 'sister'],
    moods: ['funny', 'chaotic', 'playful'],
    experienceMode: 'arcade',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Inside Joke Machine', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'aesthetic-friend',
    version: '1.0.0',
    name: 'Aesthetic Friend',
    tagline: 'Pastel hues, gentle typography, and pure serene vibes.',
    description: 'Warm cream and lavender tones with minimalist layouts, gentle micro-animations, and calming poetry.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'sister'],
    moods: ['aesthetic', 'pastel', 'minimal', 'wholesome'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Aesthetic Friend', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'sunshine',
    version: '1.0.0',
    name: 'Sunshine',
    tagline: 'For the human who brings light into everyone’s greyest days.',
    description: 'Golden hour palette radiating positive energy, compliment cards, and warm golden particles.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'mom', 'sister'],
    moods: ['sunset', 'wholesome', 'warmest', 'emotional'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Sunshine', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'cozy-corner',
    version: '1.0.0',
    name: 'Cozy Corner',
    tagline: 'Fireside warmth, cup of tea, and a heartfelt handwritten wish.',
    description: 'Hearth-like atmosphere with soft embers, comforting acoustic ambient vibes, and comforting memories.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'sister', 'mom'],
    moods: ['cozy', 'wholesome', 'handwritten'],
    experienceMode: 'room',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Cozy Corner', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'digital-letter',
    version: '1.0.0',
    name: 'Digital Letter',
    tagline: 'Wax sealed, elegantly folded, and opened with anticipation.',
    description: 'Interactive wax-seal envelope that cracks open with sound, unfolding a letter with cursive animation.',
    category: 'intimate',
    relationships: ['bestie', 'partner', 'mom', 'dad', 'sister', 'friend'],
    moods: ['handwritten', 'aesthetic', 'emotional', 'paper'],
    experienceMode: 'letter',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Digital Letter', 'letter'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'good-vibes',
    version: '1.0.0',
    name: 'Good Vibes',
    tagline: 'Nothing but love, affirmations, and celebration energy.',
    description: 'Vibrant pop-art aesthetic with uplifting compliments and bouncing confetti bursts.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'cousin', 'colleague'],
    moods: ['playful', 'wholesome', 'cute'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.playful,
    defaultScenes: DEFAULT_SCENES('Good Vibes', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'wish-jar',
    version: '1.0.0',
    name: 'Wish Jar',
    tagline: 'A glowing jar filled with wishes ready to be caught.',
    description: 'Firefly-lit glass jar with floating orbs; tap each orb to release a personal blessing into the night sky.',
    category: 'cosmic',
    relationships: ['bestie', 'friend', 'sister', 'mom', 'partner'],
    moods: ['magical', 'mystical', 'dreamy'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.nightsky,
    defaultScenes: DEFAULT_SCENES('Wish Jar', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'message-constellation',
    version: '1.0.0',
    name: 'Message Constellation',
    tagline: 'Celestial starlight mapping your journey together.',
    description: 'Astronomical observatory map connecting words and dates into a sparkling star cluster.',
    category: 'cosmic',
    relationships: ['bestie', 'partner', 'friend'],
    moods: ['cosmic', 'midnight', 'aesthetic'],
    experienceMode: 'planetarium',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.nightsky,
    defaultScenes: DEFAULT_SCENES('Message Constellation', 'planetarium'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: true,
    zeroPhotoSafe: true
  },
  {
    id: 'retro-friend',
    version: '1.0.0',
    name: 'Retro Friend',
    tagline: '90s synth vibes, neon grids, and VHS nostalgia.',
    description: 'Vaporwave color palette with nostalgic glitch reveals and upbeat synth sounds.',
    category: 'retro',
    relationships: ['bestie', 'friend', 'brother', 'cousin'],
    moods: ['retro', 'neon', 'playful'],
    experienceMode: 'arcade',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Retro Friend', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'secret-note-board',
    version: '1.0.0',
    name: 'Secret Note Board',
    tagline: 'Corkboard pinned with sticky notes and secret wishes.',
    description: 'Interactive corkboard where sticky notes flutter, flip, and reveal warm compliments.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'sister', 'colleague'],
    moods: ['cozy', 'scrapbook', 'playful'],
    experienceMode: 'room',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Secret Note Board', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'paper-story',
    version: '1.0.0',
    name: 'Paper Story',
    tagline: 'Layered paper-cut depth and tactile storybook unfolding.',
    description: 'Multi-plane papercraft landscape with pop-up book physics and delicate shadow silhouettes.',
    category: 'intimate',
    relationships: ['bestie', 'sister', 'mom', 'partner', 'friend'],
    moods: ['paper', 'aesthetic', 'fairytale'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Paper Story', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'one-day-at-a-time',
    version: '1.0.0',
    name: 'One Day at a Time',
    tagline: 'Quietly celebrating your strength, resilience, and heart.',
    description: 'Gentle, grounding presentation focusing on peace, mindfulness, and gratitude for their presence.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'sister', 'mom'],
    moods: ['cozy', 'emotional', 'minimal', 'wholesome'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('One Day at a Time', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'message-capsules',
    version: '1.0.0',
    name: 'Message Capsules',
    tagline: 'Tiny medicine for the soul: pop open whenever you need a smile.',
    description: 'Interactive pharmacy-style glass jar of pastel message capsules that pop open when tapped.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'sister'],
    moods: ['cute', 'playful', 'pastel'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.playful,
    defaultScenes: DEFAULT_SCENES('Message Capsules', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'open-when',
    version: '1.0.0',
    name: 'Open When',
    tagline: 'Envelopes marked: Open When You Need a Laugh, Open Today, Open Later.',
    description: 'Bundle of tied envelopes tailored for various emotional moments throughout their year.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'sister', 'partner', 'mom'],
    moods: ['handwritten', 'cozy', 'emotional'],
    experienceMode: 'letter',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Open When', 'letter'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'tiny-celebration',
    version: '1.0.0',
    name: 'Tiny Celebration',
    tagline: 'Micro-interactions, maximum delight.',
    description: 'Minimalist pocket celebration with a charming micro-cake, tiny candles, and a huge message.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'colleague'],
    moods: ['minimal', 'cute', 'playful'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.playful,
    defaultScenes: DEFAULT_SCENES('Tiny Celebration', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'birthday-newspaper',
    version: '1.0.0',
    name: 'Birthday Newspaper',
    tagline: 'Extra! Extra! The Most Wonderful Human Turns Another Year Finer.',
    description: 'Authentic vintage broadsheet newspaper layout with headlines, weather reports, and custom comic strips.',
    category: 'editorial',
    relationships: ['bestie', 'dad', 'mom', 'brother', 'sister', 'friend'],
    moods: ['editorial', 'paper', 'funny', 'retro'],
    experienceMode: 'newspaper',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Birthday Newspaper', 'newspaper'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'friendship-museum',
    version: '1.0.0',
    name: 'Friendship Museum',
    tagline: 'Every relic in this room tells the story of our bond.',
    description: 'Museum gallery with classical velvet ropes, pedestal displays, and spotlight illumination.',
    category: 'editorial',
    relationships: ['bestie', 'friend', 'partner'],
    moods: ['luxury', 'aesthetic', 'editorial'],
    experienceMode: 'museum',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Friendship Museum', 'museum'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'little-things',
    version: '1.0.0',
    name: 'Little Things',
    tagline: 'All the tiny habits and quirks that make you unforgettable.',
    description: 'A delicate appreciation of small details: the way they laugh, their favorite drink, their kindness.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'sister', 'partner', 'mom'],
    moods: ['wholesome', 'emotional', 'aesthetic'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Little Things', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },

  // --- SISTER EXPERIENCES ---
  {
    id: 'sister-chaos',
    version: '1.0.0',
    name: 'Sister Chaos',
    tagline: 'Stealing clothes, borrowing chargers, and loving each other fiercely.',
    description: 'Celebrates the unfiltered sister dynamic with wardrobe crime confessions and fierce loyalty.',
    category: 'sibling',
    relationships: ['sister'],
    moods: ['chaotic', 'funny', 'playful'],
    experienceMode: 'arcade',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Sister Chaos', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'big-sister-energy',
    version: '1.0.0',
    name: 'Big Sister Energy',
    tagline: 'Protective, wise, always there to bail you out.',
    description: 'Heartfelt homage honoring the guidance, protection, and unconditional safety she provides.',
    category: 'sibling',
    relationships: ['sister'],
    moods: ['wholesome', 'emotional', 'aesthetic'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Big Sister Energy', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'little-sister',
    version: '1.0.0',
    name: 'Little Sister',
    tagline: 'Forever the one who gets away with everything (and we love her for it).',
    description: 'Playful and nostalgic reflection on watching her grow while still remaining your little sister.',
    category: 'sibling',
    relationships: ['sister'],
    moods: ['cute', 'playful', 'emotional'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.playful,
    defaultScenes: DEFAULT_SCENES('Little Sister', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'annoying-but-loved',
    version: '1.0.0',
    name: 'Annoying But Loved',
    tagline: '50% arguments, 50% laughter, 100% irreplaceable.',
    description: 'Banter-filled sibling tribute acknowledging every dramatic moment and unbreakable connection.',
    category: 'sibling',
    relationships: ['sister', 'brother', 'cousin'],
    moods: ['funny', 'chaotic', 'wholesome'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Annoying But Loved', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'sister-letter',
    version: '1.0.0',
    name: 'Sister Letter',
    tagline: 'The words we don’t say out loud on regular days.',
    description: 'Deep emotional letter expressing gratitude for sharing childhood, secrets, and life.',
    category: 'sibling',
    relationships: ['sister'],
    moods: ['emotional', 'handwritten', 'intimate'],
    experienceMode: 'letter',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Sister Letter', 'letter'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'sister-arcade',
    version: '1.0.0',
    name: 'Sister Arcade',
    tagline: 'Who stole the sweater? Play to find out.',
    description: 'Interactive detective and quiz games testing how well you really know each other.',
    category: 'sibling',
    relationships: ['sister'],
    moods: ['pixel', 'playful', 'retro'],
    experienceMode: 'arcade',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Sister Arcade', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'unwritten-things',
    version: '1.0.0',
    name: 'Unwritten Things',
    tagline: 'All the silent thank-yous that never made it into birthday cards.',
    description: 'Poetic, gentle unfolding of unexpressed gratitude and sibling solidarity.',
    category: 'intimate',
    relationships: ['sister', 'brother'],
    moods: ['minimal', 'emotional', 'aesthetic'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Unwritten Things', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'sibling-hq',
    version: '1.0.0',
    name: 'Sibling HQ',
    tagline: 'Classified alliance against parental interrogations.',
    description: 'High-tech tactical briefing celebrating the sibling pact and mutual alibis.',
    category: 'sibling',
    relationships: ['sister', 'brother'],
    moods: ['playful', 'neon', 'modern'],
    experienceMode: 'room',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Sibling HQ', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'sister-awards',
    version: '1.0.0',
    name: 'Sister Awards',
    tagline: 'Winner of: Best Wingwoman, Most Dramatic Exit, and My Favorite Person.',
    description: 'Red-carpet sister trophy presentation with custom accolades and confetti.',
    category: 'sibling',
    relationships: ['sister'],
    moods: ['luxury', 'funny', 'playful'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Sister Awards', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'sister-secret-box',
    version: '1.0.0',
    name: 'Sister Secret Box',
    tagline: 'Keys, lockets, and memories only sisters share.',
    description: 'Intricately carved jewelry box with interactive compartments opening stage by stage.',
    category: 'sibling',
    relationships: ['sister'],
    moods: ['magical', 'aesthetic', 'handwritten'],
    experienceMode: 'magicbox',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Sister Secret Box', 'magicbox'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },

  // --- BROTHER & BRO EXPERIENCES ---
  {
    id: 'bro-mode',
    version: '1.0.0',
    name: 'Bro Mode',
    tagline: 'Zero cringe, straight respect, maximum hype.',
    description: 'Direct, brotherhood-centered celebration with athletic and video game hype elements.',
    category: 'sibling',
    relationships: ['brother', 'bestie', 'cousin'],
    moods: ['modern', 'playful', 'funny'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Bro Mode', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'partner-in-crime',
    version: '1.0.0',
    name: 'Partner in Crime',
    tagline: 'If we get caught, remember: we don’t know each other.',
    description: 'Action-adventure heist theme celebrating childhood escapades and lifelong backup.',
    category: 'sibling',
    relationships: ['brother', 'bestie', 'sister', 'cousin'],
    moods: ['chaotic', 'funny', 'playful'],
    experienceMode: 'arcade',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Partner in Crime', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'brother-roast',
    version: '1.0.0',
    name: 'Brother Roast',
    tagline: 'Built on a foundation of mockery and unconditional love.',
    description: 'Affectionate roast comedy show featuring your brother as the headlining star.',
    category: 'sibling',
    relationships: ['brother'],
    moods: ['funny', 'chaotic'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Brother Roast', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'brother-boss-battle',
    version: '1.0.0',
    name: 'Brother Boss Battle',
    tagline: 'Player 1 vs Player 2: Another year conquered.',
    description: 'Chiptune battle arena where the boss turns out to be an awesome, victorious brother.',
    category: 'retro',
    relationships: ['brother', 'bestie'],
    moods: ['pixel', 'retro', 'playful'],
    experienceMode: 'arcade',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Brother Boss Battle', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'legend-file',
    version: '1.0.0',
    name: 'Legend File',
    tagline: 'Documenting the rise and triumphs of an undisputed legend.',
    description: 'Hall of fame style tribute highlighting his biggest wins, character, and loyalty.',
    category: 'sibling',
    relationships: ['brother', 'bestie', 'dad'],
    moods: ['luxury', 'editorial', 'modern'],
    experienceMode: 'cinematic',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Legend File', 'cinematic'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'bro-arcade',
    version: '1.0.0',
    name: 'Bro Arcade',
    tagline: 'Arcade cabinet challenge with birthday high scores.',
    description: 'Interactive cabinet with joystick sounds, button mash celebration, and winner fanfare.',
    category: 'retro',
    relationships: ['brother', 'bestie'],
    moods: ['pixel', 'retro'],
    experienceMode: 'arcade',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Bro Arcade', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'brother-awards',
    version: '1.0.0',
    name: 'Brother Awards',
    tagline: 'Top honors for the brother who always has your back.',
    description: 'Trophy ceremony honoring brother milestones, clutch saves, and life achievements.',
    category: 'sibling',
    relationships: ['brother'],
    moods: ['luxury', 'wholesome'],
    experienceMode: 'story',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Brother Awards', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },

  // --- PARENTS & FAMILY ---
  {
    id: 'for-mom',
    version: '1.0.0',
    name: 'For Mom',
    tagline: 'For the hands that held ours and the heart that never stopped praying.',
    description: 'Deeply emotional, elegant tribute expressing the boundless gratitude owed to a mother.',
    category: 'family',
    relationships: ['mom'],
    moods: ['emotional', 'wholesome', 'warmest', 'handwritten'],
    experienceMode: 'letter',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('For Mom', 'letter'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'home',
    version: '1.0.0',
    name: 'Home',
    tagline: 'Home was never a place — it was always you.',
    description: 'Warm hearth visualizer with glowing lanterns, gentle acoustic music, and profound gratitude.',
    category: 'family',
    relationships: ['mom', 'dad', 'family', 'partner'],
    moods: ['cozy', 'emotional', 'wholesome'],
    experienceMode: 'room',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Home', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'thank-you-mom',
    version: '1.0.0',
    name: 'Thank You Mom',
    tagline: 'For all the sacrifices made in silence.',
    description: 'Graceful parchment presentation unfolding memories, life lessons, and deepest love.',
    category: 'family',
    relationships: ['mom'],
    moods: ['emotional', 'wholesome', 'handwritten'],
    experienceMode: 'letter',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Thank You Mom', 'letter'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'warmest-place',
    version: '1.0.0',
    name: 'Warmest Place',
    tagline: 'In a world that can be cold, you were always warmth.',
    description: 'Golden glowing aesthetic celebrating the sanctuary and comfort a parent created.',
    category: 'family',
    relationships: ['mom', 'dad', 'family'],
    moods: ['warmest', 'cozy', 'emotional'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Warmest Place', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'moms-memory-garden',
    version: '1.0.0',
    name: 'Mom’s Memory Garden',
    tagline: 'Every flower blooming in this garden was planted by your love.',
    description: 'Interactive botanical garden where blooming blossoms reveal memories and messages.',
    category: 'family',
    relationships: ['mom'],
    moods: ['fairytale', 'aesthetic', 'wholesome'],
    experienceMode: 'room',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Mom’s Memory Garden', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'heart-archive',
    version: '1.0.0',
    name: 'Heart Archive',
    tagline: 'Preserving the wisdom and warmth you gave our family.',
    description: 'Curated heritage archive documenting family recipes, sayings, and timeless memories.',
    category: 'family',
    relationships: ['mom', 'dad', 'family'],
    moods: ['editorial', 'wholesome', 'luxury'],
    experienceMode: 'museum',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Heart Archive', 'museum'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'for-dad',
    version: '1.0.0',
    name: 'For Dad',
    tagline: 'Quiet strength, steadfast support, and a steady hand.',
    description: 'Dignified, warm tribute honoring a father’s quiet guidance and quiet sacrifices.',
    category: 'family',
    relationships: ['dad'],
    moods: ['editorial', 'emotional', 'minimal'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('For Dad', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'my-first-hero',
    version: '1.0.0',
    name: 'My First Hero',
    tagline: 'Not all heroes wear capes — some just showed up every single day.',
    description: 'Comic-book hero tribute honoring a dad whose superpowers were patience and love.',
    category: 'family',
    relationships: ['dad'],
    moods: ['playful', 'editorial', 'wholesome'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('My First Hero', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'dad-archives',
    version: '1.0.0',
    name: 'Dad Archives',
    tagline: 'Classic dad jokes, wisdom on repeat, and an irreplaceable heart.',
    description: 'Vintage leather notebook interface honoring his humor, advice, and presence.',
    category: 'family',
    relationships: ['dad'],
    moods: ['editorial', 'paper', 'funny'],
    experienceMode: 'newspaper',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Dad Archives', 'newspaper'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'dad-command-center',
    version: '1.0.0',
    name: 'Dad Command Center',
    tagline: 'Thermostat locked, tools organized, fatherhood mastered.',
    description: 'Playful workshop garage dashboard celebrating dad quirks, projects, and proud moments.',
    category: 'family',
    relationships: ['dad'],
    moods: ['funny', 'playful', 'cozy'],
    experienceMode: 'room',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Dad Command Center', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'cousin-nights',
    version: '1.0.0',
    name: 'Cousin Nights',
    tagline: 'Family reunions survived, late-night talks remembered.',
    description: 'Cozy reunion bonfire aesthetic celebrating cousin kinship and family laughs.',
    category: 'family',
    relationships: ['cousin'],
    moods: ['cozy', 'playful', 'wholesome'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Cousin Nights', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'built-in-bestie',
    version: '1.0.0',
    name: 'Built-in Bestie',
    tagline: 'Born into the same family, chosen as my best friend.',
    description: 'Heartwarming cousin tribute celebrating growing up together through family milestones.',
    category: 'family',
    relationships: ['cousin'],
    moods: ['wholesome', 'playful', 'emotional'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.playful,
    defaultScenes: DEFAULT_SCENES('Built-in Bestie', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },

  // --- ROMANTIC & PARTNER (AGE-APPROPRIATE & ELEGANT) ---
  {
    id: 'midnight-love',
    version: '1.0.0',
    name: 'Midnight Love',
    tagline: 'Under the quiet moonlight, you are my favorite thought.',
    description: 'Deep violet, starlit aesthetic with gentle ambient glow and tender romantic reflections.',
    category: 'romantic',
    relationships: ['partner'],
    moods: ['midnight', 'romantic', 'aesthetic', 'dreamy'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.romantic,
    defaultScenes: DEFAULT_SCENES('Midnight Love', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'soft-love-letter',
    version: '1.0.0',
    name: 'Soft Love Letter',
    tagline: 'Every word written with tenderness and devotion.',
    description: 'Folded paper and wax-sealed rose gold letter with delicate floral borders and heartfelt prose.',
    category: 'romantic',
    relationships: ['partner'],
    moods: ['handwritten', 'romantic', 'emotional', 'pastel'],
    experienceMode: 'letter',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.romantic,
    defaultScenes: DEFAULT_SCENES('Soft Love Letter', 'letter'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'moonlight',
    version: '1.0.0',
    name: 'Moonlight',
    tagline: 'A quiet, glowing sky for the one who illuminates my world.',
    description: 'Silvery moonlight reflected across calm water with floating petals and serene melodies.',
    category: 'romantic',
    relationships: ['partner'],
    moods: ['dreamy', 'aesthetic', 'midnight', 'romantic'],
    experienceMode: 'nightsky',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.nightsky,
    defaultScenes: DEFAULT_SCENES('Moonlight', 'nightsky'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: true,
    zeroPhotoSafe: true
  },
  {
    id: 'our-little-world',
    version: '1.0.0',
    name: 'Our Little World',
    tagline: 'The private universe that exists only when we are together.',
    description: 'Whimsical miniature planet orbiting in space with personalized memory markers.',
    category: 'romantic',
    relationships: ['partner'],
    moods: ['magical', 'romantic', 'cosmic'],
    experienceMode: 'planetarium',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.nightsky,
    defaultScenes: DEFAULT_SCENES('Our Little World', 'planetarium'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: true,
    zeroPhotoSafe: true
  },
  {
    id: 'forever-page',
    version: '1.0.0',
    name: 'Forever Page',
    tagline: 'One page out of infinity, written for you today.',
    description: 'Timeless typographic layout with luxury serif styling and deep romantic devotion.',
    category: 'romantic',
    relationships: ['partner'],
    moods: ['luxury', 'romantic', 'editorial'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Forever Page', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'secret-garden',
    version: '1.0.0',
    name: 'Secret Garden',
    tagline: 'Behind iron gates, where gentle flowers whisper your name.',
    description: 'Enchanted gate opening to reveal illuminated vines, blooming roses, and hidden messages.',
    category: 'romantic',
    relationships: ['partner'],
    moods: ['fairytale', 'aesthetic', 'romantic'],
    experienceMode: 'room',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Secret Garden', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'cinema-for-two',
    version: '1.0.0',
    name: 'Cinema for Two',
    tagline: 'Private screening of our favorite love story.',
    description: 'Film reel projector atmosphere with vintage film transitions and romantic musical score.',
    category: 'romantic',
    relationships: ['partner'],
    moods: ['cinematic', 'romantic', 'luxury'],
    experienceMode: 'cinematic',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Cinema for Two', 'cinematic'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },

  // --- ICONIC CONCEPTUAL EXPERIENCES ---
  {
    id: 'the-room',
    version: '1.0.0',
    name: 'The Room',
    tagline: 'Explore an interactive isometric digital room filled with clues.',
    description: 'Clickable books, vinyl players, paintings, and desk lamps containing hidden birthday notes.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'sister', 'brother', 'partner'],
    moods: ['cozy', 'playful', 'aesthetic'],
    experienceMode: 'room',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('The Room', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: true,
    zeroPhotoSafe: true
  },
  {
    id: 'the-cinema',
    version: '1.0.0',
    name: 'The Cinema',
    tagline: 'Opening credits, movie scenes, sound cues, and final title card.',
    description: 'Dramatic widescreen theatrical production celebrating their existence as a masterpiece.',
    category: 'cinematic',
    relationships: ['bestie', 'friend', 'brother', 'sister', 'partner'],
    moods: ['cinematic', 'luxury', 'editorial'],
    experienceMode: 'cinematic',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('The Cinema', 'cinematic'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'the-magic-box',
    version: '1.0.0',
    name: 'The Magic Box',
    tagline: 'Virtual gift box opening progressively with surprise layers.',
    description: 'Interactive unboxing with ribbon untying physics, pop-up surprises, and final gift reveal.',
    category: 'playful',
    relationships: ['bestie', 'friend', 'sister', 'brother', 'mom', 'dad'],
    moods: ['magical', 'playful', 'wholesome'],
    experienceMode: 'magicbox',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.playful,
    defaultScenes: DEFAULT_SCENES('The Magic Box', 'magicbox'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: true,
    zeroPhotoSafe: true
  },
  {
    id: 'the-secret-mission',
    version: '1.0.0',
    name: 'The Secret Mission',
    tagline: 'Tiny interactive tasks unlock secret celebratory scenes.',
    description: 'Puzzle-solving journey unlocking cryptographic codes, hidden buttons, and agent reveals.',
    category: 'playful',
    relationships: ['brother', 'bestie', 'cousin', 'friend'],
    moods: ['playful', 'neon', 'dark'],
    experienceMode: 'story',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('The Secret Mission', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'the-arcade',
    version: '1.0.0',
    name: 'The Arcade',
    tagline: 'A playable mini-world celebrating another high score year.',
    description: 'Interactive retro arcade cabinet with sound effects, coin insert animation, and level completion.',
    category: 'retro',
    relationships: ['brother', 'bestie', 'friend', 'cousin'],
    moods: ['pixel', 'retro', 'playful'],
    experienceMode: 'arcade',
    interactionLevel: 'game',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('The Arcade', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'the-time-capsule',
    version: '1.0.0',
    name: 'The Time Capsule',
    tagline: 'Current memories plus a future letter sealed until next year.',
    description: 'Dual-layer celebration featuring present birthday wishes and a server-sealed time capsule letter.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'sister', 'brother', 'partner'],
    moods: ['mystical', 'emotional', 'wholesome'],
    experienceMode: 'timecapsule',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('The Time Capsule', 'timecapsule'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'the-dream',
    version: '1.0.0',
    name: 'The Dream',
    tagline: 'A slow, surreal visual world of floating clouds and soft reflections.',
    description: 'Ambient, meditative dreamscape with pastel clouds, slow-drifting typography, and soothing tones.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'partner', 'sister'],
    moods: ['dreamy', 'pastel', 'aesthetic', 'magical'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.nightsky,
    defaultScenes: DEFAULT_SCENES('The Dream', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: true,
    zeroPhotoSafe: true
  },
  {
    id: 'the-paper-world',
    version: '1.0.0',
    name: 'The Paper World',
    tagline: 'A layered paper-cut environment crafted just for them.',
    description: 'Exquisite multi-depth paper silhouette world with realistic lighting and physical page folds.',
    category: 'intimate',
    relationships: ['bestie', 'sister', 'mom', 'partner', 'friend'],
    moods: ['paper', 'aesthetic', 'fairytale'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('The Paper World', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'the-passport',
    version: '1.0.0',
    name: 'The Passport',
    tagline: 'A journey through chapters, stamps, and boarding passes.',
    description: 'Travel passport styling with country-style birthday entry stamps and boarding pass wishes.',
    category: 'editorial',
    relationships: ['bestie', 'friend', 'colleague', 'cousin'],
    moods: ['editorial', 'paper', 'modern'],
    experienceMode: 'passport',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('The Passport', 'passport'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'the-library',
    version: '1.0.0',
    name: 'The Library',
    tagline: 'Antique bookshelves where books open into personal chapters.',
    description: 'Majestic mahogany library where pulling books reveals chapters of your shared journey.',
    category: 'intimate',
    relationships: ['friend', 'bestie', 'dad', 'mom', 'partner'],
    moods: ['cozy', 'editorial', 'handwritten'],
    experienceMode: 'library',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('The Library', 'library'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'the-planetarium',
    version: '1.0.0',
    name: 'The Planetarium',
    tagline: 'Dome projection of celestial milestones and glowing galaxies.',
    description: 'Interactive celestial dome showing astrological star alignments, nebulae, and stellar greetings.',
    category: 'cosmic',
    relationships: ['bestie', 'partner', 'friend'],
    moods: ['cosmic', 'magical', 'midnight'],
    experienceMode: 'planetarium',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.nightsky,
    defaultScenes: DEFAULT_SCENES('The Planetarium', 'planetarium'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: true,
    zeroPhotoSafe: true
  },
  {
    id: 'luxury-black',
    version: '1.0.0',
    name: 'Luxury Black',
    tagline: 'Obsidian tones, gold accents, and pure high-fashion prestige.',
    description: 'Sophisticated matte black and gold leaf aesthetics for a refined, upscale birthday celebration.',
    category: 'cinematic',
    relationships: ['friend', 'bestie', 'colleague', 'partner', 'brother'],
    moods: ['luxury', 'editorial', 'minimal'],
    experienceMode: 'cinematic',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Luxury Black', 'cinematic'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'minimal-white',
    version: '1.0.0',
    name: 'Minimal White',
    tagline: 'Clean gallery architecture, spacious typography, modern grace.',
    description: 'Architectural minimalism focusing pure attention on words, quiet spacing, and refined elegance.',
    category: 'editorial',
    relationships: ['colleague', 'friend', 'bestie', 'partner'],
    moods: ['minimal', 'modern', 'aesthetic'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.luxury,
    defaultScenes: DEFAULT_SCENES('Minimal White', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'neon-city',
    version: '1.0.0',
    name: 'Neon City',
    tagline: 'Cyberpunk glow, rainy asphalt reflections, and neon signs.',
    description: 'Vibrant cyberpunk metropolis with neon sign flickers spelling the birthday person’s name.',
    category: 'retro',
    relationships: ['bestie', 'brother', 'friend', 'cousin'],
    moods: ['neon', 'dark', 'playful'],
    experienceMode: 'arcade',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.neon,
    defaultScenes: DEFAULT_SCENES('Neon City', 'arcade'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'fairytale',
    version: '1.0.0',
    name: 'Fairytale',
    tagline: 'Once upon a time, someone wonderful was born.',
    description: 'Illustrated fairytale book with golden illuminated manuscripts, glowing lanterns, and magical dust.',
    category: 'intimate',
    relationships: ['sister', 'mom', 'partner', 'bestie'],
    moods: ['fairytale', 'magical', 'wholesome'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.paper,
    defaultScenes: DEFAULT_SCENES('Fairytale', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'rainy-night',
    version: '1.0.0',
    name: 'Rainy Night',
    tagline: 'Cozy raindrops on the window pane, warm tea, and deep love.',
    description: 'Realistic window condensation with interactive wipe gestures revealing birthday messages.',
    category: 'intimate',
    relationships: ['bestie', 'partner', 'friend', 'sister'],
    moods: ['rainy', 'cozy', 'midnight', 'emotional'],
    experienceMode: 'room',
    interactionLevel: 'interactive',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Rainy Night', 'room'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'sunset',
    version: '1.0.0',
    name: 'Sunset',
    tagline: 'Warm gradients dipping into the horizon as a new year begins.',
    description: 'Breathtaking ocean sunset gradient that deepens into stars as the recipient scrolls through scenes.',
    category: 'intimate',
    relationships: ['bestie', 'friend', 'partner', 'mom'],
    moods: ['sunset', 'aesthetic', 'emotional'],
    experienceMode: 'story',
    interactionLevel: 'balanced',
    visualTheme: BASE_THEMES.cozy,
    defaultScenes: DEFAULT_SCENES('Sunset', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  },
  {
    id: 'cloud-nine',
    version: '1.0.0',
    name: 'Cloud Nine',
    tagline: 'Floating high above, celebrated on cloud level.',
    description: 'Drifting ethereal clouds with floating message banners and pastel rainbow refractions.',
    category: 'playful',
    relationships: ['bestie', 'sister', 'friend', 'cousin'],
    moods: ['pastel', 'cute', 'dreamy'],
    experienceMode: 'story',
    interactionLevel: 'gentle',
    visualTheme: BASE_THEMES.playful,
    defaultScenes: DEFAULT_SCENES('Cloud Nine', 'story'),
    supportsAudio: true,
    supportsVideo: true,
    supportsPhoto: true,
    supports3D: false,
    zeroPhotoSafe: true
  }
];

export function getTemplateById(id: string): TemplateDefinition {
  const found = TEMPLATES_CATALOG.find(t => t.id === id);
  return found || TEMPLATES_CATALOG[0];
}

export function getAllTemplates(): TemplateDefinition[] {
  return TEMPLATES_CATALOG;
}
